from regex_crew.tools.execute_e2b import generate_test_sandbox_for_regex, TestSuite

test_cases = TestSuite(
    valid=[
        "simple@example.com",
        "very.common@example.com",
        "disposable.style.email.with+symbol@example.com",
        "other.email-with-hyphen@example.com",
        "fully-qualified-domain@example.com",
        "user.name+tag+sorting@example.com",
        "x@example.com",
        "example-indeed@strange-example.com",
        "test/test@test.com",
        "example@s.example",
        "mailhost!username@example.org",
        "user%example.com@example.org",
        "user-@example.org",
        "postmaster@[123.123.123.123]",
        "postmaster@[IPv6:2001:0db8:85a3:0000:0000:8a2e:0370:7334]",
        'abc."defghi".xyz@example.com',
        "_______@example.com",
        "firstname+lastname@example.com",
        "1234567890@example.com",
        "user@localserver",
        "user@[2001:db8::1]",
        '" "@example.org',
        '"john..doe"@example.org',
        '"very.(),:;<>[]\\".VERY.\\"very@\\\\ \\"very\\".unusual"@strange.example.com',
    ],
    invalid=[
        "plainaddress",
        "#@%^%#$@#$@#.com",
        "@example.com",
        "Joe Smith <email@example.com>",
        "email.example.com",
        "email@example@example.com",
        ".email@example.com",
        "email.@example.com",
        "email..email@example.com",
        "あいうえお@example.com",
        "email@example.com (Joe Smith)",
        "email@example",
        "email@-example.com",
        "email@example.web",
        "email@111.222.333.44444",
        "email@example..com",
        "Abc..123@example.com",
        '"(),:;<>[]\\@example.com',
        'just"not"right@example.com',
        'this\\ is"really"not\\allowed@example.com',
        "email@123.123.123",
        "email@[123.123.123.123",
        "email@[123.123.123.123].",
        "email@[123.123.123.123]1",
        "email@[123.123.123.123]@",
        "user@[2001:db8::1].com",
        "user@[2001:db8:0:1]",
        "user@[2001:db8::g]",
        "Abc.example.com",
    ],
)
regex = "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$"

regex_eval = generate_test_sandbox_for_regex(regex, test_cases)

print(regex_eval)
